spring:
  application:
    name: jug-sample
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["*"]
  metrics:
    export:
      prometheus:
        enabled: true